// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountTo: typeof import('./src/components/widget/CountTo.vue')['default']
    ImageVerify: typeof import('./src/components/custom/ImageVerify.vue')['default']
    MiniCard: typeof import('./src/components/widget/MiniCard.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
