// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./../components/common/BetterScroll.vue')['default']
    CountTo: typeof import('./../components/widget/CountTo.vue')['default']
    ImageVerify: typeof import('./../components/custom/ImageVerify.vue')['default']
    MiniCard: typeof import('./../components/widget/MiniCard.vue')['default']
    NaiveProvider: typeof import('./../components/common/NaiveProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
